# Change these first
owner: srinath2125
repo: upptime

sites:
  - name: Srinath Upptime
    url: https://srinath2125.github.io/upptime/
    method: HEAD
    maxResponseTime: 6000
    status: 200
    checkCertificate: true
  - name: GOOGLE
    url: https://www.google.com/
  - name: Wikipedia
    url: https://www.wikipedia.org/

alerts:
  timeout: 60  # Alert if the site is down for more than 60 minutes
  commits: true  # Creates a commit in the repository when status changes
  issues: true  # Creates a GitHub issue when a site is down
  notify:
    - github  # GitHub notifications
    - email  # Email notifications

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page that uses **real-time** data from our [GitHub repository](https://github.com/srinath2125/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/srinath2125/upptime
